// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB83hh-aJzJ6pu0mun0jExuy343Io651zE',
    appId: '1:883267973376:web:aa03e6fad5b593f33203e5',
    messagingSenderId: '883267973376',
    projectId: 'healthbotapp',
    authDomain: 'healthbotapp.firebaseapp.com',
    storageBucket: 'healthbotapp.firebasestorage.app',
    measurementId: 'G-QDLN89Q276',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIxqnbpQkD61dYmlQFP1piAViV-aV2RL0',
    appId: '1:883267973376:android:f6b866a932d40d593203e5',
    messagingSenderId: '883267973376',
    projectId: 'healthbotapp',
    storageBucket: 'healthbotapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi43MXGQ_siDvof-ry3eskulgHsDbGW_I',
    appId: '1:883267973376:ios:59c0ee2a1b812b943203e5',
    messagingSenderId: '883267973376',
    projectId: 'healthbotapp',
    storageBucket: 'healthbotapp.firebasestorage.app',
    iosBundleId: 'com.example.healthAssistant',
  );
}
